# Generated by Django 2.1.3 on 2019-01-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyrim_calk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
